#config_version=6

mode:
    start_events: level2_Complete
    stop_events: level3_Complete
    priority: 100  #(100 - 1,000,000)
 
show_player:
    mode_level3_started: level3_display_loop

images:
    location3:
        load: preload
        file: /home/wicky567/PinballWW2_Master/Machine/modes/level3/images/level3_location.png
    blip3:
        load: preload
        file: /home/wicky567/PinballWW2_Master/Machine/modes/level3/images/level3_blip.png
    score3:
        load: preload
        file: /home/wicky567/PinballWW2_Master/Machine/modes/level3/images/score_overlay.png

videos:
    level3Slide1:
        width: 1920
        height: 1080
        file: /home/wicky567/PinballWW2_Master/Machine/modes/level3/videos/level3_slide1.mp4
 
    level3Slide2:
        width: 1920
        height: 1080
        file: /home/wicky567/PinballWW2_Master/Machine/modes/level3/videos/level3_slide2.mp4
 


event_player:
    mode_level3_started:
        - l3_scoreReq_Begin
    player_score{current_player.score>=300000 and current_player.is_rr == 0}: 
        - l3_scoreReq_complete
        - rr_Begin
    rr_Complete:
        - mb_Begin
        - mb_time_start
    mb_Complete:
        - level3_Complete
        - score_check
        - game_will_end


variable_player:
    mode_level3_started:
        level:
            action: set
            int: 3
        mb_time:
            action: set
            int: 20
        mb_curTime:
            action: set
            int: 20
        is_mb:
            action: set
            int: 0
    l3_scoreReq_Begin:
        cur_info:
            action: set
            string: "SCORE\n300K POINTS\nTO ADVANCE!"
    mode_restrelax_started:
        is_rr:
            action: set
            int: 1
    mode_multiball_started:
        is_mb:
            action: set
            int: 1