#config_version=6

show_player:
    mode_attract_started: attract_display_loop
    flipper_cancel:
        attract_display_loop:
            action: advance
images:
    credits:
        load: preload
        file: /home/wicky567/PinballWW2_Master/Machine/modes/attract/images/Credits.png

videos:
    mainmenu:
        width: 1920
        height: 1080
        file: /home/wicky567/PinballWW2_Master/Machine/modes/attract/videos/MainMenu.mp4
    lastscore:
        width: 1920
        height: 1080
        file: /home/wicky567/PinballWW2_Master/Machine/modes/attract/videos/LastScores.mp4
    highscore:
        width: 1920
        height: 1080
        file: /home/wicky567/PinballWW2_Master/Machine/modes/attract/videos/HighScores.mp4

assets:
    sounds:
        default:
            load: on_demand
        music:
            track: music
        main:
            file: /home/wicky567/PinballWW2_Master/Machine/modes/attract/sounds/music/main.wav